from .schemas import PromptRule


STUDENT_AGENT_SYSTEM_PROMPT = """
You are a Student Agent specialized in software architecture analysis.

Your task is to analyze the provided graph data and report:

1. Function calls found in the graph.
2. Architectural errors found in the graph.

Follow these rules:

- Use only the information provided in the graph.
- Do not invent functions, calls, errors, or line numbers.
- Every detected function call must include:
  - caller
  - callee
  - line_number
- Every reported architectural error must include:
  - error_type
  - target_node
  - line_number
- If no function calls are found, return an empty detected_calls list.
- If no architectural errors are found, return an empty reported_errors list.
- Return the result using the required StudentAgentOutput structure.
"""


def get_latest_rules(rules: list[PromptRule]) -> list[PromptRule]:
    """Keeps only the latest version of each prompt rule."""

    latest_rules: dict[str, PromptRule] = {}

    for rule in rules:
        current_rule = latest_rules.get(rule.rule_id)

        if current_rule is None or rule.version > current_rule.version:
            latest_rules[rule.rule_id] = rule

    return list(latest_rules.values())


def build_system_prompt(
    additional_rules: list[PromptRule] | None = None,
) -> str:
    """Builds a fresh system prompt with validated additional rules."""

    base_prompt = STUDENT_AGENT_SYSTEM_PROMPT.strip()

    if not additional_rules:
        return base_prompt

    latest_rules = get_latest_rules(additional_rules)

    formatted_rules = "\n".join(
        f"- {rule.rule_text}" for rule in latest_rules
    )

    return (
        f"{base_prompt}\n\n"
        "Additional rules generated by the Teacher Agent:\n"
        f"{formatted_rules}"
    )